trigger:
- main

pool:
  name: 'Default'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: type "C:\Users\user\azure\config.txt"
  displayName: 'Read and display file content'