trigger:
- main

pool:
  name: 'Default'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: type "D:\azure\config.xml"
  displayName: 'Read and display file content'